# Generated by Django 3.2.18 on 2023-04-14 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_skill_is_coding_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='Validate_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
